server.port: 8081
server.ssl.key-store: keystore.jks
server.ssl.key-store-password: password
server.ssl.keyStoreType: JKS
server.ssl.keyAlias: selfsigned

spring.data.mongodb.uri: mongodb://127.0.0.1:27017/potg

blizzard:
  client:
    clientId: n3y27fuebpcfc7zd8qfp6pxj3u8x5smn
    clientSecret: q9jSprCnsCXuQ9CJz7nCQXkNCPGufB56
    accessTokenUri: https://us.battle.net/oauth/token
    userAuthorizationUri: https://us.battle.net/oauth/authorize
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://us.api.battle.net/account/user

twitch:
  client:
    scope: channel_read
    clientId: oyn7j2cj8tzq5vimj4ttpsrkeyvy74i
    clientSecret: 10yg93q7zisygvwq98idf8vkj2gg3ld
    accessTokenUri: https://api.twitch.tv/kraken/oauth2/token
    userAuthorizationUri: https://api.twitch.tv/kraken/oauth2/authorize
    authenticationScheme: query
    clientAuthenticationScheme: form
    tokenName: oauth_token
  resource:
    userInfoUri: https://api.twitch.tv/kraken/channel

logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true
